#!/bin/bash


# Responses
E_SUCCESS="0"
E_WARNING="1"
E_CRITICAL="2"
E_UNKNOWN="3"


if [ $# -ne 1 ]; then
    printf "Usage: $0 [Health Check URL]"
    exit ${E_UNKNOWN}
fi


CURL=`which curl`
EXPECTED="success"
URL=$1


if [ -z "${CURL}" ]
then
    echo "UNKNOWN - Cannot find Curl"
    exit ${E_UNKNOWN}
fi

RESPONSE=`${CURL} -s ${URL}`

if [ "$RESPONSE" == "$EXPECTED" ]; then
    echo "OK - Response was \"$RESPONSE\""
    exit ${E_SUCCESS}
    else
    echo "CRITICAL - Response was \"$RESPONSE\""
    exit ${E_CRITICAL}
fi

